sudo: false

language: node_js
node_js:
  - "14"
  - "12"

addons:
  apt:
    packages:
    - make
    - librsvg2-bin
    - plantuml
    #- wine

# need spectron test
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"

script:
  - make ci-test

